version: '3.4'

services:
  crypto.apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Presentation/ApiGateway/Dockerfile

  crypto.brokerapi:
    image: ${DOCKER_REGISTRY-}cryptobrokerapi
    build:
      context: .
      dockerfile: Presentation/Crypto.BrokerApi/Dockerfile

  crypto.ordersapi:
    image: ${DOCKER_REGISTRY-}cryptoordersapi
    build:
      context: .
      dockerfile: Presentation/Crypto.OrdersApi/Dockerfile

  crypto.notifyapi:
    image: ${DOCKER_REGISTRY-}cryptonotifyapi
    build:
      context: .
      dockerfile: Presentation/Crypto.NotificationApi/Dockerfile

  crypto.rabbitmq:
    image: rabbitmq:3-management-alpine
