version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Presentation/ApiGateway/Dockerfile

  crypto.brokerapi:
    image: ${DOCKER_REGISTRY-}cryptobrokerapi
    build:
      context: .
      dockerfile: Presentation/Crypto.BrokerApi/Dockerfile

  crypto.ordersapi:
    image: ${DOCKER_REGISTRY-}cryptoordersapi
    build:
      context: .
      dockerfile: Presentation/Crypto.OrdersApi/Dockerfile

  notify.emailapi:
    image: ${DOCKER_REGISTRY-}notifyemailapi
    build:
      context: .
      dockerfile: Presentation/Notify.EmailApi/Dockerfile

  notify.pushapi:
    image: ${DOCKER_REGISTRY-}notifypushapi
    build:
      context: .
      dockerfile: Presentation/Notify.PushApi/Dockerfile

  notify.smsapi:
    image: ${DOCKER_REGISTRY-}notifysmsapi
    build:
      context: .
      dockerfile: Presentation/Notify.SmsApi/Dockerfile
